server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/instagram_clone?serverTimezone=UTC&autocommit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: instagramClone
  expiration: 3600000 # 1

cloud:
  aws:
    s3:
      bucket: instagram-clone-coding-bucket
    credentials:
      access-key: AKIAYMRKYYHIQMMB5UJD
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
