server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/instagram_clone?serverTimezone=UTC&autocommit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show_sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

